#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
- include_vars:
    file: common.yml

- name: Set layer's hostname
  hostname:
    name: ncn

- name: Import Shasta RPM key
  rpm_key:
    state: present
    key: https://arti.dev.cray.com/artifactory/dst-misc-stable-local/SigningKeys/HPE-SHASTA-RPM-PROD.asc

- name: Initialize cray directories
  file:
    path: /srv/cray
    state: directory
    mode: '0755'
    owner: root
    group: root
  register: create_cray_dir

- name: Add files to /srv/cray
  synchronize:
    src: files/
    dest: /srv/cray/

- name: Symlink python3 to python
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link

- name: Blacklist kernel modules
  lineinfile:
    create: yes
    path: /etc/modprobe.d/disabled-modules.conf
    regexp: 'install {{ item }} /bin/true'
    line: 'install {{ item }} /bin/true'
    state: present
  loop: "{{ kernel.blacklists.standard }}"

- name: Blacklist kernel modules for kdump
  lineinfile:
    backrefs: yes
    path: /etc/sysconfig/kdump
    regexp: '^(KDUMP_COMMANDLINE_APPEND)="(.*)"'
    line: "\\g<1>=\"module_blacklist={{ kernel.blacklists.kdump | join(',') }} \\g<2>\""

- name: Create /etc/containers
  file:
    path: /etc/containers
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create storage.conf
  file:
    path: /etc/containers/storage.conf
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: Configure podman so it will run with fuse-overlayfs
  lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^#?mount_program ='
    line: 'mount_program = "/usr/bin/fuse-overlayfs"'

- name: Get current systemd default
  command: "systemctl get-default"
  changed_when: false
  register: systemdefault

- name: Set default to multi-user target
  command: "systemctl set-default multi-user.target"
  when: "'multi-user' not in systemdefault.stdout"

- name: Initialize log directory
  file:
    path: /var/log/cray
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Initialize log file
  file:
    path: /var/log/cray/no.log
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: Copy cloud.cfg configuration
  copy:
    remote_src: yes
    src: /srv/cray/resources/common/cloud.cfg
    dest: /etc/cloud/cloud.cfg

- name: Copy motd
  copy:
    remote_src: yes
    src: /srv/cray/resources/common/motd
    dest: /etc/motd

- name: Copy logrotate configuration
  synchronize:
    src: /srv/cray/resources/common/logrotate.d/
    dest: /etc/logrotate.d/

- name: Copy sysctl configuration
  synchronize:
    src: /srv/cray/sysctl/common/
    dest: /etc/sysctl.d/

- name: Copy limit configuration
  synchronize:
    src: /srv/cray/limits/common/
    dest: /etc/security/limits.d/

- name: Install craysys shortcut into /bin
  file:
    src: /srv/cray/utilities/common/craysys/craysys
    dest: /bin/craysys
    state: link

- name: Create cray.sh profile
  file:
    path: /etc/profile.d/cray.sh
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: Export cray path
  lineinfile:
    path: /etc/profile.d/cray.sh
    regexp: '^export PYTHONPATH='
    line: 'export PYTHONPATH="/srv/cray/utilities/common"'

- name: Setup Daemons
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    masked: "{{ item.masked | default(false) }}"
  loop: "{{ services }}"
