#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
- include_vars:
    file: metal.yml

- name: Copy sysctl configuration
  synchronize:
    delete: no
    src: /srv/cray/sysctl/metal/
    dest: /etc/sysctl.d/

- name: Copy systemd configuration
  synchronize:
    delete: no
    src: /srv/cray/resources/metal/systemd/
    dest: /usr/lib/systemd/system/

- name: Copy dracut configuration
  synchronize:
    delete: no
    src: /srv/cray/resources/metal/dracut.conf.d/
    dest: /etc/dracut.conf.d/

- name: Copy sysstat cron configuration
  synchronize:
    delete: no
    src: /srv/cray/resources/metal/sysstat/
    dest: /etc/sysstat/
  register: copy_sysstat_service

- name: Copy cloud.cfg.d configuration
  synchronize:
    delete: yes
    src: /srv/cray/resources/metal/cloud/cloud.cfg.d/
    dest: /etc/cloud/cloud.cfg.d/

- name: Copy cloud templates configuration
  synchronize:
    delete: yes
    src: /srv/cray/resources/metal/cloud/templates/
    dest: /etc/cloud/templates/

- name: Copy mdadm.conf configuration
  copy:
    remote_src: yes
    src: /srv/cray/resources/metal/mdadm.conf
    dest: /etc/mdadm.conf

- name: Copy sshd_config
  copy:
    remote_src: yes
    src: /srv/cray/resources/metal/sshd_config
    dest: /etc/ssh/sshd_config

- name: Configure dhcp settings
  lineinfile:
    path: /etc/sysconfig/network/dhcp
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ dhcp }}"
- name: Disk system activity accounting
  command: "/usr/lib64/sa/sa1 -S DISK 1 1"
  when: copy_sysstat_service.changed

- name: Setup Daemons
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    masked: "{{ item.masked | default(false) }}"
    state: "{{ item.state }}"
  loop: "{{ services }}"
