= CRAY-Shasta Image Build Framework
:toc:
:toclevels: 3

== Getting Started

This repository contains the https://www.packer.io/[Packer] pipepline code for building CRAY High-Performance Computing as a Service (HPCaaS)
images for any distributable medium.

The listed software below will equip a local machine or buildserver to build for any medium (`.squashfs`, `.vbox`, `.qcow2`, `.iso`, and `vagrant`).

=== Necessary Software

* media (`.iso` or `.qcow2`) (depending on the layer)
* packer
* qemu
* envsubst
* git-vendor (for csm-rpms)
* virtualbox (optional)
* vagrant (optional)

=== Media

Packer can intake any ISO, the sections below detail utilized base ISOs in CRAY HPCaaS.

For any ISO, copy it into the `iso` directory.

==== SuSE Linux Enterprise

Files that have been tested and verified to work:
 - `SLE-15-SP2-Full-x86_64-GM-Media1.iso`
 - `SLE-15-SP3-Full-x86_64-GM-Media1.iso`
 - `SLE-15-SP3-Online-x86_64-GM-Media1.iso`

=== Repositories

You will need access to the appropriate SLES repositories in the form of official access, self-hosted access, or the provided Nexus access.

If you are using the default internal servers then you only need to pass `artifactory_user` and `artifactory_token` as variables with the packer command.

- `-var 'artifactory_user=user' -var 'artifactory_token=token'`

If you are building locally and want to provide your own repositories then the `custom_repos_file` variable must be passed with the packer command. The `custom_repos_file` variable is a filename that is placed into the `custom` folder of the project. The file must follow the same format as repos included in `csm-rpms` with the following fields: `url name flags`

- `-var 'custom_repos_file=custom.repos'`

And example entry for a custom repo:

`https://myserver.net/sles-mirror/Products/SLE-Module-Basesystem/15-SP3/x86_64/product     SUSE-SLE-Module-Basesystem-15-SP3-x86_64-Pool     -g -p 99  suse/SLE-Module-Basesystem/15-SP3/x86_64/product`

Furthermore, there may be additional repos used that are defined in `csm-rpms` which is checked out in the Quick Start section. You may be required to replace some or all of these files in `csm-rpms/repos/*.repos` to work with your environment.

==== Working with CSM-RPMS

  If you need to adjust the version of `csm-rpms` in your repo, or make changes to the `csm-rpms` code base, you will
  need to install git-vendor, which uses git submodules for managing dependencies.

  * `git vendor list` will show you the managed repos
  * `git vendor update csm-rpms release/1.2` will checkout the `release/1.2` branch of `csm-rpms`
  * All code for `csm-rpms` is stored in the `vendor` directory

=== Build Steps

* There are two Providers that can be built; VirtualBox and QEMU
* VirtualBox is best for local development.
* QEMU is best for pipeline and portability on linux machines.
* Both outputs are capable of creating the kernel, initrd, and squashfs required to boot nodes.

==== Setup

* Install packer from a reputable endpoint, like *https://www.packer.io/downloads.html[this one]*.

If you are building QEMU images in MacOS, you will need to adjust specific QEMU options:

* MacOS requires HVF for acceleration
* MacOS uses Cocoa for output
* `-var 'qemu_display=cocoa' -var 'qemu_accelerator=hvf'`


==== Prerequisites

* Setup environment variables by copying `scripts/environment.template` to `scripts/environment` and modifying the values for your environment.
* Ensure that `SLE-15-SP3-Full-x86_64-GM-Media1.iso` is in the `iso/` folder
* Execute `source scripts/environment`
* Execute `./scripts/setup.sh`
* Render the autoinst template


==== Quick Start

```bash
git clone https://github.com/Cray-HPE/node-image-build.git
cd node-image-build
cp scripts/environment.template scripts/environment
vim scripts/environment
source scripts/environment
mkdir -p iso
wget https://<somepath>/SLE-15-SP3-Full-x86_64-GM-Media1.iso -O iso/SLE-15-SP3-Full-x86_64-GM-Media1.iso
./scripts/setup.sh
```

==== Base Layer

The base layer will install SLES 15 and prepare the image for the installation of Kubernetes and Ceph.

Execute the following commands from the top level of the project

To build with QEMU, run the following command.

* Run `packer build -only=qemu.sles15-base -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' boxes/sles15-base/`

To build with VirtualBox, run the following command.

* Run `packer build -only=virtualbox-iso.sles15-base -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' boxes/sles15-base/`

If you want to view the output of the build, disable `headless` mode:

* Run `packer build -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' -var 'headless=false' boxes/sles15-base/`

Once the images are built, the output will be placed in the `output-sles15-base` directory in the root of the project.

==== Common Layer

The common layer starts from the output of the base layer. As such the base layer must be created before building common.

To build with QEMU, run the following command.

* Run `packer build -only=qemu.ncn-common -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' boxes/ncn-common/`

To build with VirtualBox, run the following command.

* Run `packer build -only=virtualbox-ovf.ncn-common -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' boxes/ncn-common/`

Once the image is built, the output will be placed in the `output-ncn-common` directory in the root of the project.

==== Pit Common Layer

The pit common layer starts from the output of the base layer. As such the base layer must be created before building pit common.

To build with QEMU, run the following command.

* Run `packer build -only=qemu.pit-common -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' boxes/pit-common/`

To build with VirtualBox, run the following command.

* Run `packer build -only=virtualbox-ovf.pit-common -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' boxes/pit-common/`

Once the image is built, the output will be placed in the `output-pit-common` directory in the root of the project.

==== Non-Compute Node Image Layer

The ncn-node-images stage builds on top of the common layer to create functional images for Kubernetes and Ceph.

To build with QEMU, run the following command.

* Run `packer build -only=qemu.* -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' boxes/ncn-node-images/`

To build with VirtualBox, run the following command.

* Run `packer build -only=virtualbox-ovf.* -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' boxes/ncn-node-images/`

Once the images are built, the output will be placed in the `output-sles15-images` directory in the root of the project.

==== Vagrant

Vagrant boxes are only configured to build from the output of the VirtualBox builds. In order to create Vagrant boxes
you will first need to create the base image and the relevant node-image for Kubernetes and Ceph.

To build vagrant boxes, run the following command:

* Run `packer build -force -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD'; boxes/sles15-vagrant/`

If you only want to build Kubernetes or Ceph, limit the build:

* Run `packer build -only=virtualbox-ovf.kubernetes -force -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' boxes/sles15-vagrant/`

If you want to view the output of the build, disable `headless` mode:

* Run `packer build -force -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' -var 'headless=false' boxes/sles15-vagrant/`

`# vagrant box add --force --name sles15sp3 ./sles15-base-virtualbox.box`

=== Artifacts

Each layer creates a certain set of artifacts that can be used in different ways.

* Each layer creates a VM disk image that can be directly booted and/or used to create the next layer's image.
* Each layer after `sles15-base` creates a list of packages and repos.
* `ncn-common` creates kernel and initrd artifacts.
* `ncn-node-images` creates kernel, initrd, and squashfs artifacts.

=== Versioning

* The version of the build is passed with the `packer build` command as the `artifact_version` var:

```bash
packer build -only=qemu.sles15-base -var "artifact_version=`git rev-parse --short HEAD`" -var 'ssh_password=$SLES15_INITIAL_ROOT_PASSWORD' -var 'headless=false' boxes/sles15-base/
````

* If no version is passed to the builder then the version `none` is used when generating the archive.