apiVersion: "kubeadm.k8s.io/v1beta2"
kind: ClusterConfiguration
kubernetesVersion: "v${KUBERNETES_PULL_VERSION}"
etcd:
    local:
        serverCertSANs:
        - "${K8S_NODE_IP}"
        peerCertSANs:
        - "${K8S_NODE_IP}"
        extraArgs:
            initial-cluster: ${ETCD_INITIAL_CLUSTER_STRING}
            initial-cluster-state: new
            name: ${ETCD_HOSTNAME}
            listen-peer-urls: https://${K8S_NODE_IP}:2380
            listen-client-urls: https://${K8S_NODE_IP}:2379
            advertise-client-urls: https://${K8S_NODE_IP}:2379
            initial-advertise-peer-urls: https://${K8S_NODE_IP}:2380
