# Copyright 2018, 2019, Cray Inc. All Rights Reserved.
---
- name: Validate Ceph Install
  any_errors_fatal: true
  run_once: true
  block:
   - name: Check for Required Ceph Services
     command: ceph -s
     retries: 5
     delay: 2
     changed_when: false
     register: ceph_mon_status
     when:
       - groups['mons'] is defined

   - debug:
      msg: "{{ ceph_mon_status.stdout_lines }}"

   - fail:
       msg: |
              "Failed Ceph Install Validation on Missing Services.  Please diagnose and re-run crayctl ceph-install"
              "HEALTH_WARN is OK if all the services are present and will typically get cleaned up in follow on plays"
     when: >
       'mon:' not in ceph_mon_status.stdout or
       'HEALTH_CRITICAL' in ceph_mon_status.stdout or
       'mgr:' not in ceph_mon_status.stdout or
       'osd:' not in ceph_mon_status.stdout or
       'mds:' not in ceph_mon_status.stdout or
       'rgw:' not in ceph_mon_status.stdout
