#!/usr/bin/env ansible-playbook

# Copyright 2018, 2019, Cray Inc. All Rights Reserved.
---

- hosts: mons
  any_errors_fatal: false
  remote_user: root
  roles:
    - ceph-rgw-users
    # Still need ceph-rbd to setup some pre-configuration
    - ceph-rbd
    - ceph-health
    - ceph-pool-quotas
    ## Commenting out old provisioner will remove after final testing of ceph-csi
    #- ceph-cephfs
