#!/usr/bin/env ansible-playbook

# Copyright 2018, 2019, Cray Inc. All Rights Reserved.
---

- hosts: ceph_all
  any_errors_fatal: false
  remote_user: root
  roles:
    - ceph-rgw-cert-authority
    - ceph-rgw-certs
