#!/usr/bin/env ansible-playbook

# Copyright 2018, 2019, Cray Inc. All Rights Reserved.

---
- hosts:
    - rgws
  any_errors_fatal: true
  remote_user: root
  tasks:
    - name: add STS settings for radosgw
      blockinfile:
        path: /etc/ceph/ceph.conf
        block: |
          rgw_s3_auth_use_sts = True
          rgw_sts_key = X66epaskQQrk+7B2
        insertafter: "client.rgw.{{ ansible_hostname }}.rgw0"
      ignore_errors: true
    - name: Restart radosgw
      systemd:
        state: restarted
        daemon_reload: yes
        name: "ceph-radosgw@rgw.{{ ansible_hostname }}.rgw0"
