#!/usr/bin/env ansible-playbook

# Copyright 2018, 2019, Cray Inc. All Rights Reserved.

---
- hosts:
    - rgwloadbalancers
  any_errors_fatal: true
  remote_user: root
  tasks:
    - name: add access for apparmor
      lineinfile:
        path: /etc/apparmor.d/usr.sbin.haproxy
        line: "  /etc/ceph/rgw.pem r,"
        insertbefore: '/usr/sbin/haproxy'
        regexp: '/etc/ceph/'
      ignore_errors: true
    - name: Restart apparmor
      systemd:
        state: restarted
        daemon_reload: yes
        name: apparmor.service

