version = 2

# set containerd as a subreaper on linux when it is not running as PID 1
subreaper = true
# set containerd's OOM score
oom_score = -999

[metrics]
  address = "0.0.0.0:1338"

[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = "${K8S_IMAGE_REGISTRY}/pause:${PAUSE_VERSION}"
  [plugins."io.containerd.grpc.v1.cri".containerd]
    snapshotter = "overlayfs"

    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
      runtime_type = "io.containerd.runc.v2"

  [plugins."io.containerd.grpc.v1.cri".cni]
    max_conf_num = 1

  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."gcr.io".auth]
        username = "_json_key"
        password = '${SERVICE_ACCOUNT_KEY}'
