---

- name: Symlink python3 to python
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link

- name: Ensure /srv/cray/utilities locations are available for use system-wide
  file:
    src: /srv/cray/utilities/common/craysys/craysys
    dest: /bin/craysys
    state: link

- name: Ensure craysys is executable
  file:
    path: /srv/cray/utilities/common/craysys/craysys
    state: file
    mode: a+x

- name: Create cray.sh profile
  file:
    path: /etc/profile.d/cray.sh
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: Export cray path
  lineinfile:
    path: /etc/profile.d/cray.sh
    regexp: '^export PYTHONPATH='
    line: 'export PYTHONPATH="/srv/cray/utilities/common"'

- name: Create /etc/containers
  file:
    path: /etc/containers
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create storage.conf
  file:
    path: /etc/containers/storage.conf
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: Configure podman so it will run with fuse-overlayfs
  lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^#?mount_program ='
    line: 'mount_program = "/usr/bin/fuse-overlayfs"'

- name: Get current systemd default
  command: "systemctl get-default"
  changed_when: false
  register: systemdefault

- name: Set default to multi-user target
  command: "systemctl set-default multi-user.target"
  when: "'multi-user' not in systemdefault.stdout"

- name: Setup Daemons
  systemd:
    enabled: "{{ item.enabled }}"
    name: "{{ item.name }}"
    masked: "{{ item.masked | default(false) }}"
    state: "{{ item.state }}"
  with_items: "{{ services_common }}"
