version = 2

# set containerd as a subreaper on linux when it is not running as PID 1
subreaper = true
# Set containerd's OOM score
oom_score = -999

[metrics]
  address = "0.0.0.0:1338"

[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = "${K8S_IMAGE_REGISTRY}/pause:${PAUSE_VERSION}"
  [plugins."io.containerd.grpc.v1.cri".containerd]
    snapshotter = "native"

    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
      runtime_type = "io.containerd.runc.v2"

  [plugins."io.containerd.grpc.v1.cri".cni]
    max_conf_num = 1

  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."dtr.dev.cray.com"]
        endpoint = ["http://pit.nmn:5000/v2/dtr.amslabs.hpecorp.net", "http://pit.nmn:5000/v2/dtr.dev.cray.com", "http://pit.nmn:5000", "http://registry.local/v2/dtr.amslabs.hpecorp.net", "http://registry.local/v2/dtr.dev.cray.com", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."arti.dev.cray.com"]
        endpoint = ["http://pit.nmn:5000/v2/arti.amslabs.hpecorp.net", "http://pit.nmn:5000/v2/arti.dev.cray.com", "http://pit.nmn:5000", "http://registry.local/v2/arti.amslabs.hpecorp.net", "http://registry.local/v2/arti.dev.cray.com", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."dtr.amslabs.hpecorp.net"]
        endpoint = ["http://pit.nmn:5000/v2/dtr.amslabs.hpecorp.net", "http://pit.nmn:5000", "http://registry.local/v2/dtr.amslabs.hpecorp.net", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."arti.amslabs.hpecorp.net"]
        endpoint = ["http://pit.nmn:5000/v2/arti.amslabs.hpecorp.net", "http://pit.nmn:5000", "http://registry.local/v2/arti.amslabs.hpecorp.net", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."artifactory.algol60.net"]
        endpoint = ["http://pit.nmn:5000/v2/artifactory.algol60.net", "http://pit.nmn:5000","http://registry.local/v2/artifactory.algol60.net", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["http://pit.nmn:5000/v2/docker.io", "http://pit.nmn:5000", "http://registry.local/v2/docker.io", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry-1.docker.io"]
        endpoint = ["http://pit.nmn:5000/v2/docker.io", "http://pit.nmn:5000", "http://registry.local/v2/docker.io", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
        endpoint = ["http://pit.nmn:5000/v2/quay.io", "http://pit.nmn:5000", "http://registry.local/v2/quay.io", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
        endpoint = ["http://pit.nmn:5000/v2/gcr.io", "http://pit.nmn:5000", "http://registry.local/v2/gcr.io", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
        endpoint = ["http://pit.nmn:5000/v2/k8s.gcr.io", "http://pit.nmn:5000", "http://registry.local:5000/v2/k8s.gcr.io", "http://registry.local:5000"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
        endpoint = ["http://pit.nmn:5000/v2/ghcr.io", "http://pit.nmn:5000", "http://registry.local/v2/ghcr.io", "http://registry.local"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.opensource.zalan.do"]
        endpoint = ["http://pit.nmn:5000/v2/registry.opensource.zalan.do", "http://pit.nmn:5000", "http://registry.local/v2/registry.opensource.zalan.do", "http://registry.local"]
