version = 2

# set containerd as a subreaper on linux when it is not running as PID 1
subreaper = true
# Set containerd's OOM score
oom_score = -999

[metrics]
  address = "0.0.0.0:1338"

[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = "k8s.gcr.io/pause:3.2"
  [plugins."io.containerd.grpc.v1.cri".containerd]
    snapshotter = "native"

    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
      runtime_type = "io.containerd.runc.v2"

  [plugins."io.containerd.grpc.v1.cri".cni]
    max_conf_num = 1

  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."arti.dev.cray.com"]
        endpoint = ["http://pit.nmn:5000/v2/arti.dev.cray.com", "https://registry.local/v2/arti.dev.cray.com", "dummy://arti.dev.cray.com"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."artifactory.algol60.net"]
        endpoint = ["http://pit.nmn:5000/v2/artifactory.algol60.net", "https://registry.local/v2/artifactory.algol60.net", "dummy://artifactory.algol60.net"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["http://pit.nmn:5000/v2/docker.io", "https://registry.local/v2/docker.io", "dummy://docker.io"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry-1.docker.io"]
        endpoint = ["http://pit.nmn:5000/v2/docker.io", "https://registry.local/v2/docker.io", "dummy://registry-1.docker.io"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
        endpoint = ["http://pit.nmn:5000/v2/quay.io", "https://registry.local/v2/quay.io", "dummy://quay.io"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
        endpoint = ["http://pit.nmn:5000/v2/gcr.io", "https://registry.local/v2/gcr.io", "dummy://gcr.io"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
        endpoint = ["http://pit.nmn:5000/v2/k8s.gcr.io", "https://registry.local/v2/k8s.gcr.io", "dummy://k8s.gcr.io"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
        endpoint = ["http://pit.nmn:5000/v2/ghcr.io", "https://registry.local/v2/ghcr.io", "dummy://ghcr.io"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.opensource.zalan.do"]
        endpoint = ["http://pit.nmn:5000/v2/registry.opensource.zalan.do", "https://registry.local/v2/registry.opensource.zalan.do", "dummy://registry.opensource.zalan.do"]
