name: "Pull Request Labeler"
on:
  pull_request:
    branches:
      - main
      - lts/csm-1.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
