---
- name: Get key for Ceph pool
  command: "ceph auth get-key client.{{ item.pool_name }}"
  register: pool_keys
  no_log: true
  loop: "{{ outer_loop }}"

- name: Create temporary file for Ceph pool key
  tempfile:
    state: file
    prefix: "{{ item.namespace }}-{{ item.name }}"
    suffix: .key
  register: "ceph_keyfile"
  loop: "{{ outer_loop }}"
- name: Write key for Ceph pool to temporary file
  copy:
    content: "{{ hostvars[groups['mons'][0]]['pool_keys']['results'][idx]['stdout'] }}"
    dest: "{{ item.path }}"
  loop: "{{ ceph_keyfile.results }}"
  loop_control:
    index_var: idx
  register: file_details

- name: print file path
  debug:
    msg: |
      - file details: "{{ item.item.path }}"
      - namespace: "{{ item.item.item.namespace }}"
  with_items: "{{ file_details.results }}"

- name: Create Kubernetes secret for Ceph pool key
  shell: "kubectl --namespace={{ item.item.item.namespace }} create secret generic {{ item.item.item.secret }} --from-file={{ item.item.path }} --type=kubernetes.io/rbd --save-config --dry-run -o yaml | kubectl apply -f -"
  register: ceph_rbd_pool_secret
  changed_when: ceph_rbd_pool_secret.rc == 0 and "unchanged" not in ceph_rbd_pool_secret.stdout
  loop: "{{ file_details.results }}"
  loop_control:
    index_var: idx
 
